authors = ["<oss@fastly.com>"]
description = "Implements Fanout handlers for WebSockets, SSE, etc."
language = "rust"
manifest_version = 2
name = "Push messaging using Fanout"
service_id = "IGtPV5En80mE9jJ6s83RJ0"
